<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>7b800723-cd71-4cc1-99c9-f43fde8ff727</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FireflyAPI.Application\FireflyAPI.Application.csproj" />
      <ProjectReference Include="..\FireflyAPI.Domain\FireflyAPI.Domain.csproj" />
      <ProjectReference Include="..\FireflyAPI.Infrastructure\FireflyAPI.Infrastructure.csproj" />
    </ItemGroup>

</Project>
